const mongoose = require("mongoose");
const { MONGO_URI } = require("./config");
const Product = require("./models/Product");

const products = [
  {
    name: "Men's Casual Shirt",
    category: "Men",
    price: 899,
    originalPrice: 1299,
    images: ["https://picsum.photos/id/1011/800/800"],
    description: "Slim-fit cotton shirt for daily wear.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.2,
    inStock: true,
  },
  {
    name: "Women's Denim Jacket",
    category: "Women",
    price: 1999,
    originalPrice: 2499,
    images: ["https://picsum.photos/id/1025/800/800"],
    description: "Trendy denim jacket with soft lining.",
    sizes: ["S", "M", "L"],
    rating: 4.6,
    inStock: true,
  },
  {
    name: "Running Shoes",
    category: "Footwear",
    price: 2599,
    originalPrice: 3499,
    images: ["https://picsum.photos/id/1042/800/800"],
    description: "Lightweight running shoes with cushioned sole.",
    sizes: ["7", "8", "9", "10", "11"],
    rating: 4.4,
    inStock: true,
  },
  {
    name: "Men's Formal Pants",
    category: "Men",
    price: 1499,
    originalPrice: 2199,
    images: ["https://picsum.photos/id/1005/800/800"],
    description: "Classic formal trousers made of stretch cotton.",
    sizes: ["30", "32", "34", "36"],
    rating: 4.1,
    inStock: true,
  },
  {
    name: "Women's Maxi Dress",
    category: "Women",
    price: 1799,
    originalPrice: 2599,
    images: ["https://picsum.photos/id/1003/800/800"],
    description: "Elegant floral print maxi dress for summer.",
    sizes: ["S", "M", "L"],
    rating: 4.5,
    inStock: true,
  },
  {
    name: "Unisex Hoodie",
    category: "Unisex",
    price: 1299,
    originalPrice: 1999,
    images: ["https://picsum.photos/id/1012/800/800"],
    description: "Cozy fleece hoodie for all-day comfort.",
    sizes: ["S", "M", "L", "XL"],
    rating: 4.3,
    inStock: true,
  },
  {
    name: "Men's Leather Jacket",
    category: "Men",
    price: 3499,
    originalPrice: 4999,
    images: ["https://picsum.photos/id/1006/800/800"],
    description: "Premium brown leather jacket with zipper pockets.",
    sizes: ["M", "L", "XL"],
    rating: 4.8,
    inStock: true,
  },
  {
    name: "Women's Sneakers",
    category: "Footwear",
    price: 2299,
    originalPrice: 2899,
    images: ["https://picsum.photos/id/1033/800/800"],
    description: "Comfortable lace-up sneakers for everyday use.",
    sizes: ["5", "6", "7", "8"],
    rating: 4.7,
    inStock: true,
  },
  {
    name: "Analog Wrist Watch",
    category: "Accessories",
    price: 2999,
    originalPrice: 3999,
    images: ["https://picsum.photos/id/100/800/800"],
    description: "Minimalist analog watch with leather strap.",
    rating: 4.4,
    inStock: true,
  },
  {
    name: "Aviator Sunglasses",
    category: "Accessories",
    price: 1299,
    originalPrice: 1799,
    images: ["https://picsum.photos/id/1015/800/800"],
    description: "Classic aviator sunglasses with UV protection.",
    rating: 4.3,
    inStock: true,
  },
  {
    name: "Sports T-shirt",
    category: "Men",
    price: 699,
    originalPrice: 999,
    images: ["https://picsum.photos/id/1008/800/800"],
    description: "Breathable quick-dry sports t-shirt.",
    rating: 4.2,
    inStock: true,
  },
  {
    name: "Women's Handbag",
    category: "Accessories",
    price: 2399,
    originalPrice: 3199,
    images: ["https://picsum.photos/id/1021/800/800"],
    description: "Leather tote bag with gold-toned hardware.",
    rating: 4.5,
    inStock: true,
  },
  {
    name: "Men's Sneakers",
    category: "Footwear",
    price: 2799,
    originalPrice: 3599,
    images: ["https://picsum.photos/id/1022/800/800"],
    description: "Stylish white sneakers with cushioned sole.",
    rating: 4.4,
    inStock: true,
  },
  {
    name: "Casual Backpack",
    category: "Accessories",
    price: 1499,
    originalPrice: 2199,
    images: ["https://picsum.photos/id/1018/800/800"],
    description: "Durable and lightweight backpack for daily use.",
    rating: 4.3,
    inStock: true,
  },
  {
    name: "Men's Jeans",
    category: "Men",
    price: 1599,
    originalPrice: 2299,
    images: ["https://picsum.photos/id/1002/800/800"],
    description: "Stretchable slim-fit jeans in dark blue.",
    rating: 4.1,
    inStock: true,
  },
  {
    name: "Women's Kurti",
    category: "Women",
    price: 1299,
    originalPrice: 1899,
    images: ["https://picsum.photos/id/1001/800/800"],
    description: "Cotton kurti with traditional patterns.",
    rating: 4.6,
    inStock: true,
  },
  {
    name: "Smartwatch",
    category: "Accessories",
    price: 4999,
    originalPrice: 6999,
    images: ["https://picsum.photos/id/1039/800/800"],
    description: "Touchscreen smartwatch with fitness tracking.",
    rating: 4.5,
    inStock: true,
  },
  {
    name: "Heels for Women",
    category: "Footwear",
    price: 1999,
    originalPrice: 2599,
    images: ["https://picsum.photos/id/1031/800/800"],
    description: "Elegant high heels for special occasions.",
    rating: 4.4,
    inStock: true,
  },
  {
    name: "Men's Polo Shirt",
    category: "Men",
    price: 999,
    originalPrice: 1399,
    images: ["https://picsum.photos/id/1016/800/800"],
    description: "Cotton polo shirt with embroidered logo.",
    rating: 4.2,
    inStock: true,
  },
  {
    name: "Women’s Leggings",
    category: "Women",
    price: 799,
    originalPrice: 1099,
    images: ["https://picsum.photos/id/1029/800/800"],
    description: "Soft stretch leggings for daily comfort.",
    rating: 4.3,
    inStock: true,
  },
];



async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    await Product.deleteMany({});
    await Product.insertMany(products);
    console.log("✅ Database seeded with working Unsplash images");
    process.exit(0);
  } catch (err) {
    console.error("❌ Error seeding database:", err);
    process.exit(1);
  }
}

seed();
